# Generated by Django 4.1.7 on 2023-03-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['author', '-publish']},
        ),
    ]
